chat/urls.py
from django.urls import path
from . import views
app_name = 'chat'
urlpatterns = [
    path('', views.messages_page, name="messages_page"),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('admin/', admin.site.urls),
	path('users/', include('users.urls')),
	path('', include('learning_logs.urls')),
    path('todo/', include('todo.urls')),
    path('chat/', include('chat.urls')),
    path('connect/', include('connect.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path, include
from . import views
app_name = 'learning_logs'
urlpatterns = [
	# Home page
	path('', views.index, name='index'),
	# Page that shows all topics.
	path('topics/', views.topics, name='topics'),
	# Detail page for a single topic.
	path('topics/<int:topic_id>/', views.topic, name='topic'),
	# Page for adding a new topic
	path('new_topic/', views.new_topic, name='new_topic'),
	# Page for adding a new entry
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	# Page for editing an entry.
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
  path('todo/',include('todo.urls',namespace='todo')),
  path('chat/',include('chat.urls',namespace='chat')),
	path('connect/',include('connect.urls',namespace='connect')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	# Include default auth urls.
	path('', include('django.contrib.auth.urls')),
	# Registration page.
	path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
	"""A topic the user is learning about."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""Return a string representation of the model."""
		return self.text

class Entry(models.Model):
	"""Something specific learned about a topic."""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	entry_image = models.ImageField(null=True, blank=True, upload_to="images/")  
    
class Meta:
	verbose_name_plural = 'entries'
	def __str__(self):
		"""Return a string representation of the model."""
		return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms
from .models import Topic, Entry
class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}
class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ('text', 'entry_image')
		labels = {'text': '','entry_image': '',}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
	"""The home page for Learning Log."""
	return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
	"""Show all topics."""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
	"""Show a single topic and all its entries."""
	topic = Topic.objects.get(id=topic_id)
	# Make sure the topic belongs to the current user.
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
	"""Add a new topic."""
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = TopicForm()
	else:
		# POST data submitted; process data.
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('learning_logs:topics')

	# Display a blank or invalid form.
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	"""Add a new entry for a particular topic."""
	topic = Topic.objects.get(id=topic_id)
	
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = EntryForm()
	else:
		# POST data submitted; process data.
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return redirect('learning_logs:topic', topic_id=topic_id)
	# Display a blank or invalid form.
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	"""Edit an existing entry."""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# Initial request; pre-fill form with the current entry.
		form = EntryForm(instance=entry)
	else:
		# POST data submitted; process data.
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('learning_logs:topic', topic_id=topic.id)
	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <style> 
      #navbar {
        overflow: hidden;
        background-color: lavender;
        padding: 90px 10px;
        transition: 0.4s;

        width: 100%;
        top: 0;
        z-index: 99;
      }

      #navbar a {
        float: left;
        color: black;
        text-align: center;
        padding: 12px;
        text-decoration: none;
        font-size: 18px; 
        line-height: 25px;
        border-radius: 4px;
      }

      #logo {
        font-size: 35px;
        background-color: greenyellow;
        font-weight: bold;
        transition: 0.4s;
      }

      #navbar a:hover {
        background-color: #ddd;
        color: black;
      }

      #navbar a.active {
        background-color: dodgerblue;
        color: white;
      }

      #navbar-right {
        float: right;
      }

      @media screen and (max-width: 580px) {
        #navbar {
          padding: 20px 10px !important;
        }
        #navbar a {
          float: none;
          display: block;
          text-align: left;
        }
        #navbar-right {
          float: none;
        }
      }
      /* Full-width input fields */
      input[type=text], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
      }

      /* Set a style for all buttons */
      button {
        background-color: #04AA6D;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
      }

      button:hover {
        opacity: 0.8;
      }

      /* Extra styles for the cancel button */
      .cancelbtn {
        width: auto;
        padding: 10px 18px;
        background-color: #f44336;
      }

      /* Center the image and position the close button */
      .imgcontainer {
        text-align: center;
        margin: 24px 0 12px 0;
        position: relative;
      }

      img.avatar {
        width: 40%;
        border-radius: 50%;
      }

      .container {
        padding: 16px;
      }

      span.psw {
        float: right;
        padding-top: 16px;
      }

      /* The Modal (background) */
      .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        padding-top: 60px;
      }

      /* Modal Content/Box */
      .modal-content {
        background-color: #fefefe;
        margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
      }

      /* The Close Button (x) */
      .close {
        position: absolute;
        right: 25px;
        top: 0;
        color: #000;
        font-size: 35px;
        font-weight: bold;
      }

      .close:hover,
      .close:focus {
        color: red;
        cursor: pointer;
      }

      /* Add Zoom Animation */
      .animate {
        -webkit-animation: animatezoom 0.6s;
        animation: animatezoom 0.6s
      }

      @-webkit-keyframes animatezoom {
        from {-webkit-transform: scale(0)} 
        to {-webkit-transform: scale(1)}
      }

      @keyframes animatezoom {
        from {transform: scale(0)} 
        to {transform: scale(1)}
      }

      /* Change styles for span and cancel button on extra small screens */
      @media screen and (max-width: 300px) {
        span.psw {
           display: block;
           float: none;
        }
        .cancelbtn {
           width: 100%;
        }
      }
    </style>
  
  
  </head>
    <body>
      <p>

       <div id="navbar">
	     <a href="{% url 'learning_logs:index' %}" style= "font-family:Raleway;font-size:35px;margin-right:50px">Let's Connect! - 
         <br>
         <br>
         
       </a> 
	       {% if user.is_authenticated %}

		  <a href="{% url 'users:logout' %}"style= "font-family:Raleway;font-size:25px;margin-right:50px">- Log out -</a>
	         {% else %}
		  <a href="{% url 'users:register' %}"style= "font-family:Raleway;font-size:25px;margin-right:50px">Register</a> -
		  <a href="{% url 'users:login' %}"style= "font-family:Raleway;font-size:25px;margin-right:50px">Log in </a>
	         {% endif %}
        <a style= "font-family:Raleway;font-size:25px;margin-right:50px">Hello {{ user.username  }}</a> 
         <a>       Please have a pleasant Visit in our website!   </a>
      </p>
      </div> 

      <script>
      // When the user scrolls down 80px from the top of the document, resize the navbar's padding and the logo's font size
      window.onscroll = function() {scrollFunction()};

      function scrollFunction() {
        if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
          document.getElementById("navbar").style.padding = "30px 10px";
          document.getElementById("logo").style.fontSize = "25px";
        } else {
          document.getElementById("navbar").style.padding = "80px 10px";
          document.getElementById("logo").style.fontSize = "35px";
        }
      }
      </script>


    </body>



</html>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}

	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

	<p>Edit entry:</p>

	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save changes</button>
	</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Let's Connect</title>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <style>
        html {
            height: 100%;
            width: 100%;
        }

        /* Slideshow container */
        .slideshow-container {
            position: relative;
            margin: auto;
        }

        /* Next & previous buttons */
        .prev, .next {
            cursor: pointer;
            position: absolute;
            top: 50%;
            width: auto;
            padding: 16px;
            margin-top: -22px;
            color: white;
            font-weight: bold;
            font-size: 18px;
            transition: 0.6s ease;
            border-radius: 0 3px 3px 0;
            user-select: none;
        }

        /* Position the "next button" to the right */
        .next {
            right: 0;
            border-radius: 3px 0 0 3px;
        }

        /* On hover, add a black background color with a little bit see-through */
        .prev:hover, .next:hover {
            background-color: rgba(0,0,0,0.8);
        }

        /* Caption text */
        .text {
            color: #f2f2f2;
            font-size: 15px;
            padding: 8px 12px;
            position: absolute;
            bottom: 8px;
            width: 100%;
            text-align: center;
        }

        /* Number text (1/3 etc) */
        .numbertext {
            color: #f2f2f2;
            font-size: 12px;
            padding: 8px 12px;
            position: absolute;
            top: 0;
        }

        /* The dots/bullets/indicators */
        .dot {
            cursor: pointer;
            height: 15px;
            width: 15px;
            margin: 0 2px;
            background-color: #bbb;
            border-radius: 50%;
            display: inline-block;
            transition: background-color 0.6s ease;
        }

        .active, .dot:hover {
            background-color: #717171;
        }

        /* Fading animation */
        .fade {
            animation-name: fade;
            animation-duration: 1.5s;
        }

        @keyframes fade {
            from {opacity: .4}
            to {opacity: 1}
        }

        /* On smaller screens, decrease text size */
        @media only screen and (max-width: 300px) {
            .prev, .next,.text {font-size: 11px}
        }

        /* Additional text */
        .additional-text {
            color: black;
            font-size: 35px;
            font-family: Raleway;
            position: absolute;
            top: 70px;
            right: 80px;
            transform: translate(-40%, -100%);
            width: 100%;
            text-align: right;
            word-spacing: 5px;
            line-height: 60px;
            text-align: right;
        }

        /* Smaller text */
        .smaller-text {
            color: black;
            font-size: 20px;
            position: absolute;
            top: 90px;
            right: 80px;
            transform: translate(-50%, -50%);
            width: 100%;
            text-align: center;
            word-spacing: 5px;
            text-align: right;
            line-height: 35px;
        }

        /* Button styles */
        .btn {
            background-color: #38a89b;
            color: white;
            border: none;
            padding: 5px 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 25px;
            position: absolute;
            top: 70%;
            left: 50%;
            transform: translate(-50%, -50%);
            cursor: pointer;
            border-radius: 60px;
        }
        
    </style>
</head>
<body>
<header>
    <h1 style="font-family: Raleway;"><u>Welcome to Let's Connect!</u></h1>
    
    <script src="{% static 'js/login.js' %}"></script>
    <div class="slideshow-container">
        <div class="mySlides fade">
            <div class="numbertext">1 / 5</div>
            <div style="position: relative;">
                <img src="{% static 'pictures/puzzlepeople.svg' %}" style="width:100%; height:500px" alt="dna1">
                <button class="btn view" onclick="window.location.href='{% url 'learning_logs:topics' %}'">Topics</button>
            </div>
            <div class="additional-text">
                What is "Let's Connect"<br>
            </div>
            <div style="color:08c5bc" class="smaller-text">
                A website that helps you in many aspects of your life<br>
                ensuring a smooth experience!
            </div>
        </div>

        <div class="slideshow-container">
            <div class="mySlides fade">
                <div class="numbertext">2 / 5</div>
                <div style="position: relative;">
                    <img src="{% static 'pictures/chatting.png' %}" style="width:100%; height:500px" alt="dna1">
                    <button class="btn view" onclick="window.location.href='{% url 'chat:messages_page' %}'">Connect to Friends!</button>
                </div>
                <div class="additional-text">
                    Lets connect offers chatting"<br>
                </div>
                <div style="right:20px" class="smaller-text">
                    Helping you stay messaging with your friends<br>
                    
                </div>
            </div>


                    <div class="slideshow-container">
                        <div class="mySlides fade">
                            <div class="numbertext">3 / 5</div>
                            <div style="position: relative;">
                                <img src="{% static 'pictures/todo.jpg' %}" style="width:100%; height:500px" alt="dna1">
                                <button class="btn view" onclick="window.location.href='{% url 'todo:index' %}'">Todo</button>
                            </div>
                            <div style="right:5px;top:100px;font-size:28"; class="additional-text">
                                Need to get organized with your tasks? 
                            </div>

                            <div style="right:-130px;top:120px"; class="smaller-text">
                                We've got your back! Our todo app enables you to effortlessly add <br> delete tasks as needed, ensuring you stay on top of your to-do list."

                            </div>
                        </div>
                </div>
                <div class="slideshow-container">
                    <div class="mySlides fade">
                        <div class="numbertext">4 / 5</div>
                        <div style="position: relative;">
                            <img src="{% static 'pictures/EHS.png' %}" style="width:100%; height:500px" alt="todo">
                            <button class="btn view" onclick="window.location.href='{% url 'todo:index' %}'">Todo</button>
                        </div>
                        <div class="additional-text">
                            A to-do List! To ensure your up to task with everything!"<br>
                        </div>
                        <div class="smaller-text">
                           You add a new to-do by pressing publish<br>
                        </div>
                    </div>
                    <div class="slideshow-container">
                        <div class="mySlides fade">
                            <div class="numbertext">5 / 5</div>
                            <div style="position: relative;">
                                <img src="{% static 'pictures/graphicmess.jpg' %}" style="width:100%; height:500px" alt="todo">
                                <button class="btn view" onclick="window.location.href='{% url 'connect:index' %}'">Connect to World</button>
                            </div>
                            <div class="additional-text">
                                A functioning chatting application<br>
                            </div>
                            <div class="smaller-text">
                               You add a new to-do by pressing publish<br>
                            </div>
                        </div>

        <a class="prev" onclick="plusSlides(-1)">❮</a>
        <a class="next" onclick="plusSlides(1)">❯</a>
    </div>

    <br>
    <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span> 
        <span class="dot" onclick="currentSlide(2)"></span> 
        <span class="dot" onclick="currentSlide(3)"></span> 
        <span class="dot" onclick="currentSlide(4)"></span>
        <span class="dot" onclick="currentSlide(5)"></span>

        <p style= "font-family:Raleway;font-size:28px">
            ⦿We believe greatness resides in everyone. Yet, life's challenges often make it difficult to accomplish everything alone. But you don't have to. Let's Connect and forge a bond together. Whether it's conquering late nights or seeking companionship during tough times, we're here for each other, every step of the way.
            
        </p>
        
        
        
        
        
        <footer>
          <p>
              ⦿ Project manager: Nilabhro 
              <br>
              ⦿ Front End: Emerson 
              <br>
              ⦿Back end: Mohammad -
              <br>
              If you have any questions please email at this address:
          <a href="nilabhropal17@gmail.com">nilabhropal17@gmail.com</a></p>
        </footer>

        



        
    </div>

    <script>
    let slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        let i;
        let slides = document.getElementsByClassName("mySlides");
        let dots = document.getElementsByClassName("dot");
        if (n > slides.length) {slideIndex = 1}    
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";  
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";  
        dots[slideIndex-1].className += " active";
    }
    </script>

</header>

{% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
</form>

<script src="{% static 'script.js' %}"></script>
<script src="https://medium.com/@kiranpk189"></script>

    <p>  </p>
</body>
</html>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
	<p>Add a new entry:</p>
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Add entry</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
	<p>Add a new topic:</p>
	<form action="{% url 'learning_logs:new_topic' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Add topic</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
	<p>Topic: {{ topic }}</p>
	<p>Entries:</p>
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
	</p>

	<ul>
	{% for entry in entries %}
		<li>
			<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
			<p>{{ entry.text|linebreaks }}</p>
			<p>
				<a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
			</p>
		</li>
	{% empty %}
		<li>There are no entries for this topic yet.</li>
	{% endfor %}
	</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content %}
	<p>Topics</p>
	<ul>
		{% for topic in topics %}
			<li>
				<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</li>
		{% empty %}
			<li>No topics have been added yet.</li>
		{% endfor %}
	</ul>
	<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}